### ISSUE TITLE
Localised Time

### ISSUE THREAD

**Issue by ogoletti** [jeroenheijmans/advent-of-code-charts#71]
Not sure if I missed it, but would it be possible to have localised time in the "Time" columns.

**Comment by jeroenheijmans** [comment]
Can you elaborate? Are you talking about this table?

![part 1, delta, and part 2 times](https://user-images.githubusercontent.com/1590536/205313525-9927da42-db6f-4246-8aeb-3f61408a8133.png)

Because that doesn't show "Time of Day" but "Time Taken" (so a "timespan"), which is the same regardless of your locale.

**Comment by ogoletti** [comment]
Time spent since the release of the puzzle (so basically UTC-5) if I'm not mistaken. 
It kind of translate to a time of the day somehow.
And as such could be more readable if localised.

**Comment by jeroenheijmans** [comment]
Hmmm, I see your point, but it really is intended to be "*Time since puzzle was released*" (which indeed happens to be midnight UTC-5), similar to how "Time" is used as a term on [the personal stats](https://adventofcode.com/2022/leaderboard/self) page.

I understand it can be confusing if leaderboards and "time taken" are not top of mind, or if you have a leaderboard where everyone "agrees" to start at some other point in time it might also be different; then a localized variant might be useful. Just not sure if I want to add toggles or settings (making things more complex) to cater for every type of context.

Put differently: for me, and for many others too I presume, the "time taken since released" interpretation is the reasonable default.

Will let your question/suggestion sink in a bit more though. (And either way: thanks for taking the time to write your feedback!)

**Comment by ogoletti** [comment]
No worries. It isn't really necessary. 
We don't care about time anyway. 
I found your plugin because I wanted to be able to sort on "delta time" anyway. 
Then I thought it'd be more readable (for me) if the "Time" column actually meant anything to me... 
But I hadn't realised at that moment that it actually was "Time" since release intedended for competitive players. (Do you really wake up at 6AM for the puzzles?)

**Comment by jeroenheijmans** [comment]
Haha :D indeed I live in West-EU and get up 05:50 at least for the first few days. This year's hectic for me personally so not sure if I'll keep it up for too long 😂 

The "Delta Time" is the main reason for that table to be there too by the way. It gives _some_ way of comparing performance against friends and colleagues, in a manner neutral to what time you start puzzling.

I'll leave the issue open and give it a bit more thought, but might indeed close it later.

Glad the plugin was helpful regardless, and: happy puzzling! :)

**Comment by jeroenheijmans** [comment]
I was considering this for #79 (2023) but I think I will stick with the existing situation, where "Time" means "time taken" regardless of time zone. This is consistent with how the AoC website does things e.g. on [The Personal Stats page](https://adventofcode.com/2022/leaderboard/self). Hope that makes sense.

Thanks for taking the time to provide feedback!
