### ISSUE TITLE
Minutes taken for second star graph

### ISSUE THREAD

**Issue by enigma** [jeroenheijmans/advent-of-code-charts#77]
Some of us play with friends across timezone and like to compare performance by delta time, at the moment they're not the easiest to compare visually as it appears on top of the time took for the first star.

This seems to have been previously considered in https://github.com/jeroenheijmans/advent-of-code-charts/issues/40#issuecomment-740932876.  That was closed without the graph part but are PR still welcome?

# Proposals
1. One good chart would be similar to `Stars vs Log10(minutes taken per star)` but with two changes:
    
      - For each day consider only players that have 2 stars.
      - On the y-axis add a point per day at `y = delta time` (that is `part2 - part1`) rather than from competition start.
      - Optionally in linear scale filtering out delta times > 240' as in the bottom chart.
    
2. An easier alternative may be to add a toggle on the last chart `Minutes taken per start - top 3 players` to only consider star2.
3. Probably even easier is to swap the stacking of star1 and star2 in that last chart, which maybe could be done by swapping [these two lines](https://github.com/jeroenheijmans/advent-of-code-charts/blob/master/src/js/app.js#L992-L993).

**Comment by jeroenheijmans** [comment]
Thanks for taking the time to open such a well thought out issue! 🙏

I'm certainly open to PR's though for such a somewhat larger suggestion I would like to think on it first (and am on holidays until the 29th) - but for sure such an addition is worthwhile and can go into the extension at some point!

The issue you link to did get resolved and in the mean time folks can already use the delta time column in the per-day stats to get a little bit already.

PS. Note #69: I will only get to this after Dec 2022, and not entirely sure when. Just so you know!

Thx again for the suggestions 😊

**Comment by jeroenheijmans** [comment]
I'm still not so much in love with that last `Stars vs Log10...` chart, so I'm trying to avoid using it (I might slash it at some point). However, @enigma you wrote as your core request:

> Some of us play with friends across timezone and like to compare performance by delta time, at the moment they're not the easiest to compare visually

In #58 someone made a PR that might solve this issue (will land via #79 for 2023), because I expanded that PR into a full-blown delta-time based leaderboard. A sneak preview from development looks like this:

![image](https://user-images.githubusercontent.com/1590536/211116306-13ec060f-1215-40b4-b1ec-8e278ba57950.png)

It's a custom leaderboard, where you score points each day based on the delta time _only_, and are ranked amongst your leaderboard buddies accordingly.

I'm going to _presume_ that this actually fixes your feature request for the moment. But do ping me if you feel this issue should be reopened, and let us know what different things you think are needed?

Thanks either way for the suggestion and input!
